### ISSUE TITLE
Holiday 2024 - Idea/Project List

### ISSUE THREAD

**Issue by binaryn3xus** [binaryn3xus/HomeOps#2439]
# TODO
- [x] Kubernetes - Upgrade Talos
- [x] Kubernetes - Fix Loki/Grafana
- [x] Kubernetes- Update dev container for homeops
- [x] Kubernetes - Self-hosted AI Coding Chatbot
- [x] Kubernetes - Fix Minio Login Issue
- [x] Infrastructure - Shelly Radio Signal Boost
- [x] Infrastructure - Install Inovelli switch
- [x] Infrastructure - Joplin Notes
- [x] Infrastructure - Run Ethernet for Living Room TV (Move away from Wifi)
- [x] Home-Assistant - Weird HASS + Google Home issue
- [x] Home-Assistant - UI Rework
- [x] Node-Red - Clean up
- [x] Node-Red - Fix living room TV notification

# Nevermind
- [x] Kubernetes - Postgres Cluster - (No longer needed for now)
- [x] Kubernetes - Look into Syncthings - (Current backup solution is fine)
